#app≈‰÷√
server:
  port: 8082
  servlet:
    context-path: /sell
#spring≈‰÷√
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#log≈‰÷√
logging:
  pattern:
#    console: "%d - %msg%n"
#  path: O:/logs/tomcat
  file: O:/logs/tomcat/sell.log
#  level: debug
#  level:
#    org.shao.LoggerTest: debug